CREATE TABLE CLIENTE_RECETA(
ID_CLIENTE Number ,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
ID_RECETA  Number 
);

ALTER TABLE CLIENTE_RECETA
ADD constraint PK_CLIENTE_RECETA
Primary Key(ID_CLIENTE,ID_RECETA);

ALTER TABLE CLIENTE_RECETA
ADD constraint FK1_CLIENTE_RECETA
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE_INFORMACION_PERSONAL(ID_CLIENTE)
ON DELETE CASCADE;

ALTER TABLE CLIENTE_RECETA
ADD constraint FK2_CLIENTE_RECETA
FOREIGN KEY(ID_RECETA)
REFERENCES RECETA_INFORMACION_CONSULTA(ID_RECETA)
ON DELETE CASCADE;

