COMMENT ON TABLE CLIENTE_INFORMACION_CONTACTO IS "La información de la direccion, telefono y Correo Electronico del Cliente";
COMMENT ON TABLE CLIENTE_INFORMACION_PERSONAL IS "La informacion personal del cliente que son nombre(s), Apellido Materno, Apellido Paterno e ID";
COMMENT ON TABLE EMPLEADO_INFORMACION_CONTACTO IS "La informacion de la direccion, telefono y Correo Electronico de un Empleado";
COMMENT ON TABLE EMPLEADO_INFORMACION_PERSONAL IS "La informacion personal del empleado que son nombre(s), Apellido Materno, Apellido Paterno, su Numero de Seguro Social y RFC";
COMMENT ON TABLE MEDICO_INFORMACION_CONTACTO IS "La informacion de la direccion, telefono y Correo Electronico de un Medico";
COMMENT ON TABLE MEDICO_INFORMACION_PERSONAL IS "La informacion personal del medico que son nombre(s), Apellido Materno, Apellido Paterno, Numero de Seguro Social, RFC y Cedula Profesional";
COMMENT ON TABLE MEDICO_INFORMACION_SUCURSAL IS "Nos da la informacion de la sucursal donde trabaja el Medico";

COMMENT ON COLUMN CLIENTE_INFORMACION_CONTACTO.NOMBRE IS "El nombre del cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_CONTACTO.APELLIDO_MATERNO IS "El apellido Materno del Cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_CONTACTO.Apellido_PATERNO IS "El apellido Paterno del Cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_CONTACTO.DIRECCION IS "La direccion de la vivienda del Cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_CONTACTO.TELEFONO IS "El numero telefonico del cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_CONTACTO.CORREO_ELECTRONICO IS "El Correo Electronico del Cliente";

COMMENT ON COLUMN CLIENTE_INFORMACION_PERSONAL.ID_CLIENTE IS "El id del cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_PERSONAL.NOMBRE IS "El nombre del Cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_PERSONAL.APELLIDO_MATERNO IS "El Apellido Materno del Cliente";
COMMENT ON COLUMN CLIENTE_INFORMACION_PERSONAL.APELLIDO_PATERNO IS "El Apellido Paterno del Cliente";

COMMENT ON COLUMN EMPLEADO_INFORMACION_CONTACTO.RFC IS "El RFC del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_CONTACTO.NOMBRE IS "El nombre del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_CONTACTO.APELLIDO_MATERNO IS "El Apellido Materno del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_CONTACTO.APELLIDO_PATERNO IS "El Apellido Paterno del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_CONTACTO.DIRECCION IS "La direccion del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_CONTACTO.CORREO_ELECTRONICO IS "El Correo Electronico del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_CONTACTO.TELEFONO IS "El telefono del Empleado";

COMMENT ON COLUMN EMPLEADO_INFORMACION_PERSONAL.NO_SEGURO_SOCIAL IS "El numero de Seguro Social del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_PERSONAL.RFC IS "El RFC del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_PERSONAL.NOMBRE IS "El Nombre del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_PERSONAL.APELLIDO_PATERNO IS "El Apellido Paterno del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_PERSONAL.APELLIDO_MATERNO IS "El Apellido Materno del Empleado";

COMMENT ON COLUMN EMPLEADO_INFORMACION_SUCURSAL.NO_SEGURO_SOCIAL IS "El numero de Seguro Social del Empleado";
COMMENT ON COLUMN EMPLEADO_INFORMACION_SUCURSAL.SUCURSAL IS "Nos dice la Sucursal donde trabaja el Empleado";

COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.NO_SEGURO_SOCIAL IS "El numero de Seguro Social del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.CEDULA_PROFESIONAL IS "La Cedula Profesional del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.NOMBRE IS "El nombre del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.APELLIDO_PATERNO IS "El Apellido Paterno del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.APELLIDO_MATERNO IS "El Apellido Materno del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.DIRECCION IS "La direccion de la vivienda del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.TELEFONO IS "El telefono del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_CONTACTO.CORREO_ELECTRONICO IS "El Correo Electronico del Medico";

COMMENT ON COLUMN MEDICO_INFORMACION_PERSONAL.NO_SEGURO_SOCIAL IS "El numero de Seguro Social del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_PERSONAL.RFC IS "El RFC del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_PERSONAL.CEDULA_PROFESIONAL IS "La Cedula Profesional del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_PERSONAL.NOMBRE IS "El Nombre del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_PERSONAL.APELLIDO_PATERNO IS "El Apellido Paterno del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_PERSONAL.APELLIDO_MATERNO IS "El Apellido Materno del Medico";

COMMENT ON COLUMN MEDICO_INFORMACION_SUCURSAL.NO_SEGURO_SOCIAL IS "El numero de Seguro Social del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_SUCURSAL.CEDULA_PROFESIONAL IS "La Cedula Profesional del Medico";
COMMENT ON COLUMN MEDICO_INFORMACION_SUCURSAL.SUCURSAL IS "Nos da el nombre de la sucursal donde trabaja el Medico";