CREATE TABLE COMPRA_INFORMACION_GENERAL(
ID_Compra Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Receta Number ,
Sucursal Number NOT NULL,
Vendedor Number NOT NULL,
Fecha Date NOT NULL,
Total NUMBER(9,0) NOT NULL,
Tipo_Pago VARCHAR(255) NOT NULL
);

ALTER TABLE COMPRA_INFORMACION_GENERAL
ADD constraint PK_COMPRA_GENERAL
Primary Key(ID_Compra);

CREATE TABLE COMPRA_INFORMACION_SUCVEN(
Sucursal NUMBER NOT NULL,
Vendedor NUMBER NOT NULL
);

ALTER TABLE COMPRA_INFORMACION_SUCVEN
ADD constraint PK_COMPRA_PRODUCTO
Primary Key(Vendedor);

ALTER TABLE COMPRA_INFORMACION_GENERAL
ADD constraint FK1_INFORMACION_GENERAL
FOREIGN KEY(Vendedor)
REFERENCES COMPRA_INFORMACION_SUCVEN(Vendedor)
ON DELETE CASCADE;