CREATE TABLE CLIENTE_INFORMACION_PERSONAL(
ID_CLIENTE Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL
);

ALTER TABLE CLIENTE_INFORMACION_PERSONAL
ADD constraint PK_CLIENTE_PERSONAL
Primary Key(ID_CLIENTE);

ALTER TABLE  CLIENTE_INFORMACION_PERSONAL
ADD constraint FK1_CLIENTE_PERSONAL
FOREIGN KEY(Nombre,Apellido_Materno,Apellido_Paterno)
REFERENCES CLIENTE_INFORMACION_CONTACTO(Nombre,Apellido_Materno,Apellido_Paterno)
ON DELETE CASCADE;


CREATE TABLE CLIENTE_INFORMACION_CONTACTO(
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL
);


ALTER TABLE CLIENTE_INFORMACION_CONTACTO
ADD constraint PK1_CLIENTE_CONTACTO
PRIMARY KEY(Nombre, Apellido_Materno, Apellido_Paterno);

CREATE TABLE EMPLEADO_INFORMACION_PERSONAL(
ID_CLIENTE Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint PK_EMPLEADO_PERSONAL
Primary Key(ID_CLIENTE,No_Seguro_Social,RFC);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint FK1_EMPLEADO_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES EMPLEADO_INFORMACION_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;


CREATE TABLE EMPLEADO_INFORMACION_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE EMPLEADO_INFORMACION_CONTACTO
ADD constraint PK_Empleado_Contacto
Primary Key(RFC,Nombre);


CREATE TABLE EMPLEADO_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal VARCHAR(255) NOT NULL
);

ALTER TABLE EMPLEADO_INFORMACION_SUCURSAL
ADD constraint PK1_EMPLEADO_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint FK2_EMPLEADO_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES EMPLEADO_INFORMACION_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;

CREATE TABLE MEDICO_INFORMACION_PERSONAL(
ID_CLIENTE Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint PK_MEDICO_PERSONAL
Primary key(ID_CLIENTE,No_Seguro_Social,RFC,Cedula_Profesional);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint FK1_MEDICO_PERSONAL
FOREIGN KEY(No_Seguro_Social,Cedula_Profesional,Nombre,Apellido_Materno,Apellido_Paterno)
REFERENCES MEDICO_INFORMACION_CONTACTO(No_Seguro_Social,Cedula_Profesional,Nombre,Apellido_Materno,Apellido_Paterno)
ON DELETE CASCADE;

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint FK2_MEDICO_PERSONAL
FOREIGN KEY(No_Seguro_Social,Cedula_Profesional)
REFERENCES MEDICO_INFORMACION_SUCURSAL(No_Seguro_Social,Cedula_Profesional)
ON DELETE CASCADE;

CREATE TABLE MEDICO_INFORMACION_CONTACTO(
No_Seguro_Social VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL
);


ALTER TABLE MEDICO_INFORMACION_CONTACTO
ADD constraint PK_MEDICO_CONTACTO
Primary key(No_Seguro_Social,Cedula_Profesional,Nombre,Apellido_Materno,Apellido_Paterno);

CREATE TABLE MEDICO_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
SUCURSAL VARCHAR(255) NOT NULL
);

ALTER TABLE MEDICO_INFORMACION_SUCURSAL
ADD constraint PK_MEDICO_SUCURSAL
Primary key(No_Seguro_Social,Cedula_Profesional);

CREATE TABLE COMPRA_INFORMACION_GENERAL(
ID_Compra Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Receta Integer,
Sucursal VARCHAR(255),
Vendedor VARCHAR(255)
);

ALTER TABLE COMPRA_INFORMACION_GENERAL
ADD constraint PK_COMPRA_GENERAL
Primary Key(ID_Compra,No_Receta);

ALTER TABLE COMPRA_INFORMACION_GENERAL
ADD constraint FK1_COMPRA_GENERAL
FOREIGN KEY(Sucursal)
REFERENCES COMPRA_INFORMACION_PRODUCTO(Sucursal)
ON DELETE CASCADE;

ALTER TABLE COMPRA_INFORMACION_GENERAL
ADD constraint FK2_COMPRA_GENERAL
FOREIGN KEY(No_Receta)
REFERENCES COMPRA_INFORMACION_FECHA(No_Receta)
ON DELETE CASCADE;

CREATE TABLE COMPRA_INFORMACION_PRODUCTO(
Sucursal VARCHAR(255),
Productos VARCHAR(255),
Total INTEGER
);

ALTER TABLE COMPRA_INFORMACION_PRODUCTO
ADD constraint PK_COMPRA_PRODUCTO
Primary Key(Sucursal);


CREATE TABLE COMPRA_INFORMACION_FECHA(
No_Receta Integer,
Fecha TimeStamp
);

ALTER TABLE COMPRA_INFORMACION_FECHA
ADD constraint PK_COMPRA_FECHA
Primary Key(No_Receta);


CREATE TABLE MEDICAMENTO(
Marca VARCHAR(255),
Nombre VARCHAR(255),
Precio NUMBER(9,0),
Especialidad VARCHAR(255)
);

ALTER TABLE MEDICAMENTO
ADD constraint PK_MEDICAMENTO
Primary Key(Marca,Nombre);

CREATE TABLE RECETA_INFORMACION_MEDICO(
ID_Receta Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Medico VARCHAR(255),
Firma VARCHAR(255)
);

ALTER TABLE RECETA_INFORMACION_MEDICO
ADD constraint PK_RECETA_MEDICO
Primary Key(ID_Receta);

CREATE TABLE RECETA_INFORMACION_CONSULTA(
Medico VARCHAR(255),
Datos_Paciente VARCHAR(255),
Numero_Pacientes_Turno INTEGER,
Turno_Consulta INTEGER
);

ALTER TABLE RECETA_INFORMACION_CONSULTA
ADD constraint PK_RECETA_CONSULTA
Primary Key(Medico,Datos_Paciente);

CREATE TABLE ESPECIALIDAD(
ID_Especialidad Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Especialidad VARCHAR(255)
);

ALTER TABLE ESPECIALIDAD
ADD constraint PK_ESPECIALIDAD
Primary key(ID_Especialidad);

CREATE TABLE MEDICO_ESPECIALIDAD(
ID_CLIENTE NUMBER,
ID_Especialidad NUMBER,
No_Seguro_Social VARCHAR(255),
RFC VARCHAR(255),
Cedula_Profesional VARCHAR(255)
);

ALTER TABLE MEDICO_ESPECIALIDAD
ADD constraint PK_MEDICO_ESPECIALIDAD
PRIMARY KEY(ID_CLIENTE,ID_Especialidad,No_Seguro_Social,RFC,Cedula_Profesional);

ALTER TABLE MEDICO_ESPECIALIDAD
ADD constraint FK1_MEDICO_ESPECIALIDAD
FOREIGN KEY(ID_especialidad)
REFERENCES ESPECIALIDAD(ID_Especialidad)
ON DELETE CASCADE;


ALTER TABLE MEDICO_ESPECIALIDAD
ADD constraint FK2_MEDICO_ESPECIALIDAD
FOREIGN KEY(ID_CLIENTE,No_Seguro_Social,RFC,Cedula_Profesional)
REFERENCES MEDICO_INFORMACION_PERSONAL(ID_CLIENTE,No_Seguro_Social,RFC,Cedula_Profesional)
ON DELETE CASCADE;

CREATE TABLE TELEFONOS_SUCURSALES(
ID_Telefono Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Telefono VARCHAR(255)
);

ALTER TABLE TELEFONOS_SUCURSALES
ADD constraint PK_TELEFONOS_SUCURSALES
Primary Key(ID_Telefono);

CREATE TABLE TELEFONO_SUCURSAL(
ID_Telefono Number,
ID_Sucursal Number,
Direccion VARCHAR(255)
);

ALTER TABLE TELEFONO_SUCURSAL
ADD constraint PK_TELEFONO_SUCURSAL
Primary Key(ID_Telefono,ID_Sucursal,Direccion);

ALTER TABLE TELEFONO_SUCURSAL
ADD constraint FK1_TELEFONO_SUCURSAL
FOREIGN KEY(ID_Telefono)
REFERENCES TELEFONOS_SUCURSALES(ID_Telefono)
ON DELETE CASCADE;

ALTER TABLE TELEFONO_SUCURSAL
ADD constraint FK2_TELEFONO_SUCURSAL
FOREIGN KEY(ID_Sucursal)
REFERENCES SUCURSAL(ID_Sucursal)
ON DELETE CASCADE;

CREATE TABLE SUCURSAL(
ID_Sucursal Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Responsable VARCHAR(255),
Direccion VARCHAR(255),
Ciudad VARCHAR(255),
Estado VARCHAR(255)
);
DROP TABLE SUCURSAL;

ALTER TABLE SUCURSAL
ADD constraint PK_SUCURSAL
Primary Key(ID_Sucursal);

CREATE TABLE INGREDIENTE(
ID_Ingrediente Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Ingrediente VARCHAR(255)
);

ALTER TABLE INGREDIENTE
ADD constraint PK_INGREDIENTE
Primary Key(ID_Ingrediente);

CREATE TABLE MEDICAMENTO_INGREDIENTE(
ID_Ingrediente NUMBER,
Marca VARCHAR(255),
Nombre VARCHAR(255)
);

ALTER TABLE MEDICAMENTO_INGREDIENTE
ADD constraint PK_MEDICAMENTO_INGRDIENTE
Primary Key(ID_Ingrediente,Marca,Nombre);

ALTER TABLE MEDICAMENTO_INGREDIENTE
ADD constraint FK1_MEDICAMENTO_INGRE
FOREIGN KEY(ID_Ingrediente)
REFERENCES INGREDIENTE(ID_Ingrediente)
ON DELETE CASCADE;

ALTER TABLE MEDICAMENTO_INGREDIENTE
ADD constraint FK2_MEDICAMENTO_INGRE
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;

CREATE TABLE PRESENTACION(
ID_Presentacion Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
PRESENTACION VARCHAR(255)
);

ALTER TABLE PRESENTACION
ADD constraint PK_PRESENTACION
Primary Key(ID_Presentacion);

CREATE TABLE MEDICAMENTO_PRESENTACION(
ID_Presentacion NUMBER,
Marca VARCHAR(255),
Nombre VARCHAR(255)
);

ALTER TABLE MEDICAMENTO_PRESENTACION
ADD constraint PK_MEDICAMENTO_PRE
Primary Key(ID_Presentacion,Marca,Nombre);

ALTER TABLE MEDICAMENTO_PRESENTACION
ADD constraint FK1_MEDICAMENTO_PRE
FOREIGN KEY(ID_Presentacion)
REFERENCES PRESENTACION(ID_Presentacion)
ON DELETE CASCADE;

ALTER TABLE MEDICAMENTO_PRESENTACION
ADD constraint FK2_MEDICAMENTO_PRE
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;

CREATE TABLE CLIENTE_RECETA(
ID_CLIENTE Number ,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
ID_RECETA  Number 
);

ALTER TABLE CLIENTE_RECETA
ADD constraint PK_CLIENTE_RECETA
Primary Key(ID_CLIENTE,ID_RECETA);

ALTER TABLE CLIENTE_RECETA
ADD constraint FK1_CLIENTE_RECETA
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE_INFORMACION_PERSONAL(ID_CLIENTE)
ON DELETE CASCADE;

ALTER TABLE CLIENTE_RECETA
ADD constraint FK2_CLIENTE_RECETA
FOREIGN KEY(ID_RECETA)
REFERENCES RECETA_INFORMACION_MEDICO(ID_RECETA)
ON DELETE CASCADE;

CREATE TABLE EMPLEADO_SUCURSAL(
ID_CLIENTE Number ,
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
ID_SUCURSAL NUMBER
);

ALTER TABLE EMPLEADO_SUCURSAL
ADD constraint PK_EMPLEADO_SUCURSAL
Primary Key(ID_CLIENTE,No_Seguro_Social,RFC,ID_SUCURSAL);

ALTER TABLE EMPLEADO_SUCURSAL
ADD constraint FK1_EMPLEADO_SUCURSAL
FOREIGN KEY(ID_CLIENTE,No_Seguro_Social,RFC)
REFERENCES EMPLEADO_INFORMACION_PERSONAL(ID_CLIENTE,No_Seguro_Social,RFC)
ON DELETE CASCADE;


ALTER TABLE EMPLEADO_SUCURSAL
ADD constraint FK3_EMPLEADO_SUCURSAL
FOREIGN KEY(ID_SUCURSAL)
REFERENCES SUCURSAL(ID_SUCURSAL)
ON DELETE CASCADE;

CREATE TABLE MEDICO_RECETA(
ID_CLIENTE Number,
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
ID_RECETA NUMBER
);

ALTER TABLE MEDICO_RECETA
ADD constraint PK_MEDICO_RECETA
Primary Key(ID_CLIENTE,No_Seguro_Social,RFC,Cedula_Profesional,ID_RECETA);

ALTER TABLE MEDICO_RECETA
ADD constraint FK1_MEDICO_RECETA
FOREIGN KEY(ID_CLIENTE,No_Seguro_Social,RFC,Cedula_Profesional)
REFERENCES MEDICO_INFORMACION_PERSONAL(ID_CLIENTE,No_Seguro_Social,RFC,Cedula_Profesional)
ON DELETE CASCADE;

ALTER TABLE MEDICO_RECETA
ADD constraint FK2_MEDICO_RECETA
FOREIGN KEY(ID_RECETA)
REFERENCES RECETA_INFORMACION_MEDICO(ID_RECETA)
ON DELETE CASCADE;

CREATE TABLE SUCURSAL_MEDICAMENTO(
ID_Sucursal Number,
Responsable VARCHAR(255),
Direccion VARCHAR(255),
Ciudad VARCHAR(255),
Estado VARCHAR(255),
Marca VARCHAR(255),
Nombre VARCHAR(255),
Precio NUMBER(9,0),
Especialidad VARCHAR(255)
);



ALTER TABLE SUCURSAL_MEDICAMENTO
ADD constraint PK_SUCURSAL_MEDIC
Primary Key(ID_SUCURSAL,Marca,Nombre);

ALTER TABLE SUCURSAL_MEDICAMENTO
ADD constraint FK1_SUCURSAL_MEDIC
FOREIGN KEY(ID_SUCURSAL)
REFERENCES SUCURSAL(ID_SUCURSAL)
ON DELETE CASCADE;

ALTER TABLE SUCURSAL_MEDICAMENTO
ADD constraint FK2_SUCURSAL_MEDIC
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;

CREATE TABLE MEDICAMENTO_RECETA(
Marca VARCHAR(255),
Nombre VARCHAR(255),
Precio NUMBER(9,0),
Especialidad VARCHAR(255),
ID_Receta Number,
Medico VARCHAR(255),
Firma VARCHAR(255)
);

ALTER TABLE MEDICAMENTO_RECETA
ADD constraint PK_MEDICAMENTO_RECETA
Primary Key(Marca,Nombre,ID_RECETA);

ALTER TABLE MEDICAMENTO_RECETA
ADD constraint FK1_MEDICAMENTO_RECETA
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;

ALTER TABLE MEDICAMENTO_RECETA
ADD constraint FK2_MEDICAMENTO_RECETA
FOREIGN KEY (ID_RECETA)
REFERENCES RECETA_INFORMACION_MEDICO(ID_RECETA)
ON DELETE CASCADE;

CREATE TABLE MEDICAMENTO_COMPRA(
Marca VARCHAR(255),
Nombre VARCHAR(255),
Precio NUMBER(9,0),
Especialidad VARCHAR(255),
ID_COMPRA	NUMBER,
NO_RECETA	NUMBER
);

ALTER TABLE MEDICAMENTO_COMPRA
ADD constraint PK_MEDICAMENTO_COMPRA
Primary Key(Marca,Nombre,ID_compra,NO_Receta);

ALTER TABLE MEDICAMENTO_COMPRA
ADD constraint FK1_MEDICAMENTO_COMPRA
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;

ALTER TABLE MEDICAMENTO_COMPRA
ADD constraint FK2_MEDICAMENTO_COMPRA
FOREIGN KEY(ID_Compra,No_Receta)
REFERENCES COMPRA_INFORMACION_GENERAL(ID_COMPRA,No_Receta)
ON DELETE CASCADE;

CREATE TABLE MOSTRADOR_COMPRA(
ID_CLIENTE Number,
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
ID_Compra Number,
No_Receta Integer,
Sucursal VARCHAR(255),
Vendedor VARCHAR(255)
);

ALTER TABLE MOSTRADOR_COMPRA
ADD constraint PK_MOSTRADOR_COMPRA
Primary Key(ID_CLIENTE,No_Seguro_Social,RFC,ID_Compra,No_Receta);

ALTER TABLE MOSTRADOR_COMPRA
ADD constraint FK1_MOSTRADOR_COMPRA
FOREIGN KEY(ID_CLIENTE,No_Seguro_Social,RFC)
REFERENCES MOSTRADOR_INFO_PERSONAL(ID_CLIENTE,No_Seguro_Social,RFC)
ON DELETE CASCADE;

ALTER TABLE MOSTRADOR_COMPRA
ADD constraint FK2_MOSTRADOR_COMPRA
FOREIGN KEY(ID_Compra,No_Receta)
REFERENCES COMPRA_INFORMACION_GENERAL(ID_Compra,No_Receta)
ON DELETE CASCADE;