CREATE TABLE CLIENTE_INFORMACION_PERSONAL(
ID_CLIENTE Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Nombre VARCHAR(255) DEFAULT'Nombre Default',
Apellido_Materno VARCHAR(255) DEFAULT 'Apellido Default',
Apellido_Paterno VARCHAR(255) DEFAULT 'Apellido Default',
Monedero NUMBER(9,0)
);

ALTER TABLE CLIENTE_INFORMACION_PERSONAL
ADD constraint PK_CLIENTE_PERSONAL
Primary Key(ID_CLIENTE);


CREATE TABLE CLIENTE_INFORMACION_CONTACTO(
Nombre VARCHAR(255) DEFAULT 'Nombre Default',
Apellido_Materno VARCHAR(255) DEFAULT 'Apellido Default',
Apellido_Paterno VARCHAR(255) DEFAULT 'Apellido Default',
Direccion VARCHAR(255) DEFAULT 'Direccion Default',
Telefono VARCHAR(255) DEFAULT 'Direccion Default',
Correo_Electronico VARCHAR(255) DEFAULT 'Correo Default'
);

ALTER TABLE CLIENTE_INFORMACION_CONTACTO
ADD constraint PK1_CLIENTE_CONTACTO
PRIMARY KEY(Nombre, Apellido_Materno, Apellido_Paterno);

ALTER TABLE  CLIENTE_INFORMACION_PERSONAL
ADD constraint FK1_CLIENTE_PERSONAL
FOREIGN KEY(Nombre,Apellido_Materno,Apellido_Paterno)
REFERENCES CLIENTE_INFORMACION_CONTACTO(Nombre,Apellido_Materno,Apellido_Paterno)
ON DELETE CASCADE;

CREATE TABLE MOSTRADOR_COMPRA(
ID_CLIENTE Number,
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
ID_Compra Number,
No_Receta Integer,
Sucursal VARCHAR(255),
Vendedor VARCHAR(255)
);

ALTER TABLE MOSTRADOR_COMPRA
ADD constraint PK_MOSTRADOR_COMPRA
Primary Key(ID_CLIENTE,No_Seguro_Social,RFC,ID_Compra,No_Receta);

ALTER TABLE MOSTRADOR_COMPRA
ADD constraint FK1_MOSTRADOR_COMPRA
FOREIGN KEY(ID_CLIENTE,No_Seguro_Social,RFC)
REFERENCES MOSTRADOR_INFO_PERSONAL(ID_CLIENTE,No_Seguro_Social,RFC)
ON DELETE CASCADE;

ALTER TABLE MOSTRADOR_COMPRA
ADD constraint FK2_MOSTRADOR_COMPRA
FOREIGN KEY(ID_Compra,No_Receta)
REFERENCES COMPRA_INFORMACION_GENERAL(ID_Compra,No_Receta)
ON DELETE CASCADE;