CREATE TABLE INTENDENCIA_INFO_PERSONAL(
ID_Intendencia Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE INTENDENCIA_INFO_PERSONAL
ADD constraint PK_INTENDENCIA_PERSONAL
Primary Key(ID_Intendencia,No_Seguro_Social,RFC);

CREATE TABLE INTENDENCIA_INFO_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE INTENDENCIA_INFO_CONTACTO
ADD constraint PK_Intendencia_Contacto
Primary Key(RFC,Nombre);

ALTER TABLE INTENDENCIA_INFO_PERSONAL
ADD constraint FK1_INTENDENCIA_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES INTENDENCIA_INFO_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;

CREATE TABLE INTENDENCIA_INFO_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal NUMBER NOT NULL
);

ALTER TABLE INTENDENCIA_INFO_SUCURSAL
ADD constraint PK1_Intendencia_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE INTENDENCIA_INFO_PERSONAL
ADD constraint FK2_INTENDENCIA_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES INTENDENCIA_INFO_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;


CREATE TABLE MOSTRADOR_INFO_PERSONAL(
ID_Mostrador Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE MOSTRADOR_INFO_PERSONAL
ADD constraint PK_MOSTRADOR_PERSONAL
Primary Key(ID_Mostrador,No_Seguro_Social,RFC);

CREATE TABLE MOSTRADOR_INFO_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE MOSTRADOR_INFO_CONTACTO
ADD constraint PK_MOSTRADOR_Contacto
Primary Key(RFC,Nombre);

ALTER TABLE MOSTRADOR_INFO_PERSONAL
ADD constraint FK1_MOSTRADOR_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES MOSTRADOR_INFO_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;

CREATE TABLE MOSTRADOR_INFO_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal NUMBER NOT NULL
);

ALTER TABLE MOSTRADOR_INFO_SUCURSAL
ADD constraint PK1_MOSTRADOR_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE MOSTRADOR_INFO_PERSONAL
ADD constraint FK2_MOSTRADOR_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES MOSTRADOR_INFO_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;


CREATE TABLE GENERAL_INFO_PERSONAL(
ID_General Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE GENERAL_INFO_PERSONAL
ADD constraint PK_GENERAL_PERSONAL
Primary Key(ID_GENERAL,No_Seguro_Social,RFC);

CREATE TABLE GENERAL_INFO_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE GENERAL_INFO_CONTACTO
ADD constraint PK_GENERAL_Contacto
Primary Key(RFC,Nombre);

ALTER TABLE GENERAL_INFO_PERSONAL
ADD constraint FK1_GENERAL_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES GENERAL_INFO_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;

CREATE TABLE GENERAL_INFO_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal NUMBER NOT NULL
);

ALTER TABLE GENERAL_INFO_SUCURSAL
ADD constraint PK1_GENERAL_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE GENERAL_INFO_PERSONAL
ADD constraint FK2_GENERAL_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES GENERAL_INFO_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;


CREATE TABLE RESPONSABLE_INFO_PERSONAL(
ID_Responsable Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE RESPONSABLE_INFO_PERSONAL
ADD constraint PK_RESPONSABLE_PERSONAL
Primary Key(ID_RESPONSABLE,No_Seguro_Social,RFC);

CREATE TABLE RESPONSABLE_INFO_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE RESPONSABLE_INFO_CONTACTO
ADD constraint PK_RESPONSABLE_Contacto
Primary Key(RFC,Nombre);


ALTER TABLE RESPONSABLE_INFO_PERSONAL
ADD constraint FK1_RESPONSABLE_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES RESPONSABLE_INFO_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;


CREATE TABLE RESPONSABLE_INFO_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal NUMBER NOT NULL
);

ALTER TABLE RESPONSABLE_INFO_SUCURSAL
ADD constraint PK1_RESPONSABLE_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE RESPONSABLE_INFO_PERSONAL
ADD constraint FK2_RESPONSABLEL_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES RESPONSABLE_INFO_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;

CREATE TABLE REPARTIDOR_INFO_PERSONAL(
ID_REPARTIDOR NUMBER GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Licensia VARCHAR(255),
Vehiculo VARCHAR(255),
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE REPARTIDOR_INFO_PERSONAL
ADD constraint PK_REPARTIDOR_PERSONAL
Primary Key(ID_REPARTIDOR,No_Seguro_Social,RFC);

CREATE TABLE REPARTIDOR_INFO_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE REPARTIDOR_INFO_CONTACTO
ADD constraint PK_REPARTIDOR_CONTACTO
Primary Key(RFC,Nombre);

ALTER TABLE REPARTIDOR_INFO_PERSONAL
ADD constraint FK1_REPARTIDOR_PERSONAL
FOREIGN KEY(RFC,Nombre)
REFERENCES REPARTIDOR_INFO_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;

CREATE TABLE REPARTIDOR_INFO_SUCURSAL(
NO_SEGURO_SOCIAL VARCHAR(255),
SUCURSAL NUMBER
);

ALTER TABLE REPARTIDOR_INFO_SUCURSAL
ADD constraint PK_REPARTIDOR_SUCURSAL
Primary Key(NO_SEGURO_SOCIAL);

ALTER TABLE REPARTIDOR_INFO_PERSONAL
ADD constraint FK2_REPARTIDOR_SUCURSAL
FOREIGN KEY(NO_SEGURO_SOCIAL)
REFERENCES REPARTIDOR_INFO_SUCURSAL(NO_SEGURO_SOCIAL)
ON DELETE CASCADE;