CREATE TABLE INTENDENCIA_INFORMACION_PERSONAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE INTENDENCIA_INFORMACION_PERSONAL
ADD constraint PK_EMPLEADO_PERSONAL
Primary Key(No_Seguro_Social,RFC);

ALTER TABLE INTENDENCIA_INFORMACION_PERSONAL
ADD constraint FK1_EMPLEADO_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES EMPLADO_INFORMACION_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;


CREATE TABLE INTENDENCIA_INFORMACION_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE INTENDENCIA_INFORMACION_CONTACTO
ADD constraint PK_Empleado_Contacto
Primary Key(RFC,Nombre);


CREATE TABLE EINTENDENCIA_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal VARCHAR(255) NOT NULL
);

ALTER TABLE INTENDENCIA_INFORMACION_SUCURSAL
ADD constraint PK1_EMPLEADO_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE INTENDENCIA_INFORMACION_PERSONAL
ADD constraint FK2_EMPLEADO_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES EMPLEADO_INFORMACION_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;

CREATE TABLE MOSTRADOR_INFORMACION_PERSONAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE MOSTRADOR_INFORMACION_PERSONAL
ADD constraint PK_EMPLEADO_PERSONAL
Primary Key(No_Seguro_Social,RFC);

ALTER TABLE MOSTRADOR_INFORMACION_PERSONAL
ADD constraint FK1_EMPLEADO_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES EMPLADO_INFORMACION_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;


CREATE TABLE MOSTRADOR_INFORMACION_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE MOSTRADOR_INFORMACION_CONTACTO
ADD constraint PK_Empleado_Contacto
Primary Key(RFC,Nombre);


CREATE TABLE MOSTRADOR_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal VARCHAR(255) NOT NULL
);

ALTER TABLE MOSTRADOR_INFORMACION_SUCURSAL
ADD constraint PK1_EMPLEADO_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE MOSTRADOR_INFORMACION_PERSONAL
ADD constraint FK2_EMPLEADO_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES EMPLEADO_INFORMACION_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;

CREATE TABLE GENERAL_INFORMACION_PERSONAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE GENERAL_INFORMACION_PERSONAL
ADD constraint PK_EMPLEADO_PERSONAL
Primary Key(No_Seguro_Social,RFC);

ALTER TABLE GENERAL_INFORMACION_PERSONAL
ADD constraint FK1_EMPLEADO_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES EMPLADO_INFORMACION_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;


CREATE TABLE GENERAL_INFORMACION_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE GENERAL_INFORMACION_CONTACTO
ADD constraint PK_Empleado_Contacto
Primary Key(RFC,Nombre);


CREATE TABLE GENERAL_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal VARCHAR(255) NOT NULL
);

ALTER TABLE GENERAL_INFORMACION_SUCURSAL
ADD constraint PK1_EMPLEADO_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE GENERAL_INFORMACION_PERSONAL
ADD constraint FK2_EMPLEADO_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES EMPLEADO_INFORMACION_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;

CREATE TABLE RESPONSABLE_INFORMACION_PERSONAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE RESPONSABLE_INFORMACION_PERSONAL
ADD constraint PK_EMPLEADO_PERSONAL
Primary Key(No_Seguro_Social,RFC);

ALTER TABLE RESPONSABLE_INFORMACION_PERSONAL
ADD constraint FK1_EMPLEADO_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES EMPLADO_INFORMACION_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;


CREATE TABLE RESPONSABLE_INFORMACION_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE ERESPONSABLE_INFORMACION_CONTACTO
ADD constraint PK_Empleado_Contacto
Primary Key(RFC,Nombre);


CREATE TABLE EMPLEADO_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal VARCHAR(255) NOT NULL
);

ALTER TABLE EMPLEADO_INFORMACION_SUCURSAL
ADD constraint PK1_EMPLEADO_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint FK2_EMPLEADO_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES EMPLEADO_INFORMACION_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;