CREATE TABLE EMPLEADO_INFORMACION_PERSONAL(
ID_CLIENTE Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint PK_EMPLEADO_PERSONAL
Primary Key(ID_CLIENTE,No_Seguro_Social,RFC);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint CHECK1_EMPLEADO_PERSONAL
CHECK (LENGTH(NO_SEGURO_SOCIAL) =15);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint CHECK2_EMPLEADO_PERSONAL
CHECK (LENGTH(RFC) =13);

CREATE TABLE EMPLEADO_INFORMACION_CONTACTO(
RFC VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL
);

ALTER TABLE EMPLEADO_INFORMACION_CONTACTO
ADD constraint PK_Empleado_Contacto
Primary Key(RFC,Nombre);

ALTER TABLE EMPLEADO_INFORMACION_CONTACTO
ADD constraint CHECK1_EMPLEADO_CONTACTO
CHECK (LENGTH(RFC) =13);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint FK1_EMPLEADO_PERSONAL
FOREIGN KEY (RFC,Nombre)
REFERENCES EMPLEADO_INFORMACION_CONTACTO(RFC,Nombre)
ON DELETE CASCADE;


CREATE TABLE EMPLEADO_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Sucursal VARCHAR(255) NOT NULL
);

ALTER TABLE EMPLEADO_INFORMACION_SUCURSAL
ADD constraint PK1_EMPLEADO_SUCURSAL
Primary key(No_Seguro_Social);

ALTER TABLE EMPLEADO_INFORMACION_PERSONAL
ADD constraint FK2_EMPLEADO_SUCURSAL
FOREIGN KEY(No_Seguro_Social)
REFERENCES EMPLEADO_INFORMACION_SUCURSAL(No_Seguro_Social)
ON DELETE CASCADE;

ALTER TABLE EMPLEADO_INFORMACION_SUCURSAL
ADD constraint CHECK1_EMPLEADO_SUCURSAL
CHECK (LENGTH(NO_SEGURO_SOCIAL) =15);