CREATE TABLE MEDICAMENTO_COMPRA(
Marca VARCHAR(255),
Nombre VARCHAR(255),
Precio NUMBER(9,0),
Especialidad VARCHAR(255),
ID_COMPRA	NUMBER
);

ALTER TABLE MEDICAMENTO_COMPRA
ADD constraint PK_MEDICAMENTO_COMPRA
Primary Key(Marca,Nombre,ID_compra);

ALTER TABLE MEDICAMENTO_COMPRA
ADD constraint FK1_MEDICAMENTO_COMPRA
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;

ALTER TABLE MEDICAMENTO_COMPRA
ADD constraint FK2_MEDICAMENTO_COMPRA
FOREIGN KEY(ID_Compra)
REFERENCES COMPRA_INFORMACION_GENERAL(ID_COMPRA)
ON DELETE CASCADE;