CREATE TABLE MEDICAMENTO(
Marca VARCHAR(255),
Nombre VARCHAR(255),
Precio NUMBER(9,0),
Especialidad VARCHAR(255)
);

ALTER TABLE MEDICAMENTO
ADD constraint PK_MEDICAMENTO
Primary Key(Marca,Nombre);

CREATE TABLE INGREDIENTE(
ID_Ingrediente Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Ingrediente VARCHAR(255)
);

ALTER TABLE INGREDIENTE
ADD constraint PK_INGREDIENTE
Primary Key(ID_Ingrediente);

CREATE TABLE MEDICAMENTO_INGREDIENTE(
ID_Ingrediente NUMBER,
Marca VARCHAR(255),
Nombre VARCHAR(255)
);

ALTER TABLE MEDICAMENTO_INGREDIENTE
ADD constraint PK_MEDICAMENTO_INGRDIENTE
Primary Key(ID_Ingrediente,Marca,Nombre);

ALTER TABLE MEDICAMENTO_INGREDIENTE
ADD constraint FK1_MEDICAMENTO_INGRE
FOREIGN KEY(ID_Ingrediente)
REFERENCES INGREDIENTE(ID_Ingrediente)
ON DELETE CASCADE;

ALTER TABLE MEDICAMENTO_INGREDIENTE
ADD constraint FK2_MEDICAMENTO_INGRE
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;

CREATE TABLE PRESENTACION(
ID_Presentacion Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
PRESENTACION VARCHAR(255)
);

ALTER TABLE PRESENTACION
ADD constraint PK_PRESENTACION
Primary Key(ID_Presentacion);

CREATE TABLE MEDICAMENTO_PRESENTACION(
ID_Presentacion NUMBER,
Marca VARCHAR(255),
Nombre VARCHAR(255)
);

ALTER TABLE MEDICAMENTO_PRESENTACION
ADD constraint PK_MEDICAMENTO_PRE
Primary Key(ID_Presentacion,Marca,Nombre);

ALTER TABLE MEDICAMENTO_PRESENTACION
ADD constraint FK1_MEDICAMENTO_PRE
FOREIGN KEY(ID_Presentacion)
REFERENCES PRESENTACION(ID_Presentacion)
ON DELETE CASCADE;

ALTER TABLE MEDICAMENTO_PRESENTACION
ADD constraint FK2_MEDICAMENTO_PRE
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;
