CREATE TABLE MEDICO_INFORMACION_PERSONAL(
ID_Medico Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL
);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint PK_MEDICO_PERSONAL
Primary key(ID_Medico,No_Seguro_Social,RFC,Cedula_Profesional);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint CHECK1_MEDICO_PERSONAL
CHECK (LENGTH(NO_SEGURO_SOCIAL) =15);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint CHECK2_MEDICO_PERSONAL
CHECK (LENGTH(RFC) =13);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint CHECK3_MEDICO_PERSONAL
CHECK (LENGTH(CEDULA_PROFESIONAL) =7);


CREATE TABLE MEDICO_INFORMACION_CONTACTO(
No_Seguro_Social VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
Direccion VARCHAR(255) NOT NULL,
Telefono VARCHAR(255) NOT NULL,
Correo_Electronico VARCHAR(255) NOT NULL
);


ALTER TABLE MEDICO_INFORMACION_CONTACTO
ADD constraint PK_MEDICO_CONTACTO
Primary key(No_Seguro_Social,Cedula_Profesional,Nombre,Apellido_Materno,Apellido_Paterno);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint FK1_MEDICO_PERSONAL
FOREIGN KEY(No_Seguro_Social,Cedula_Profesional,Nombre,Apellido_Materno,Apellido_Paterno)
REFERENCES MEDICO_INFORMACION_CONTACTO(No_Seguro_Social,Cedula_Profesional,Nombre,Apellido_Materno,Apellido_Paterno)
ON DELETE CASCADE;

ALTER TABLE MEDICO_INFORMACION_CONTACTO
ADD constraint CHECK1_MEDICO_CONTACTO
CHECK (LENGTH(NO_SEGURO_SOCIAL) =15);

ALTER TABLE MEDICO_INFORMACION_CONTACTO
ADD constraint CHECK2_MEDICO_CONTACTO
CHECK (LENGTH(CEDULA_PROFESIONAL) =7);

CREATE TABLE MEDICO_INFORMACION_SUCURSAL(
No_Seguro_Social VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
SUCURSAL VARCHAR(255) NOT NULL
);

ALTER TABLE MEDICO_INFORMACION_SUCURSAL
ADD constraint PK_MEDICO_SUCURSAL
Primary key(No_Seguro_Social,Cedula_Profesional);

ALTER TABLE MEDICO_INFORMACION_PERSONAL
ADD constraint FK2_MEDICO_PERSONAL
FOREIGN KEY(No_Seguro_Social,Cedula_Profesional)
REFERENCES MEDICO_INFORMACION_SUCURSAL(No_Seguro_Social,Cedula_Profesional)
ON DELETE CASCADE;


ALTER TABLE MEDICO_INFORMACION_SUCURSAL
ADD constraint CHECK1_MEDICO_SUCURSAL
CHECK (LENGTH(NO_SEGURO_SOCIAL) =15);

ALTER TABLE MEDICO_INFORMACION_SUCURSAL
ADD constraint CHECK2_MEDICO_SUCURSAL
CHECK (LENGTH(CEDULA_PROFESIONAL) =7);

CREATE TABLE ESPECIALIDAD(
ID_Especialidad Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Especialidad VARCHAR(255)
);

ALTER TABLE ESPECIALIDAD
ADD constraint PK_ESPECIALIDAD
Primary key(ID_Especialidad);

CREATE TABLE MEDICO_ESPECIALIDAD(
ID_Medico NUMBER,
ID_Especialidad NUMBER,
No_Seguro_Social VARCHAR(255),
RFC VARCHAR(255),
Cedula_Profesional VARCHAR(255)
);

ALTER TABLE MEDICO_ESPECIALIDAD
ADD constraint PK_MEDICO_ESPECIALIDAD
PRIMARY KEY(ID_Medico,ID_Especialidad,No_Seguro_Social,RFC,Cedula_Profesional);

ALTER TABLE MEDICO_ESPECIALIDAD
ADD constraint FK1_MEDICO_ESPECIALIDAD
FOREIGN KEY(ID_especialidad)
REFERENCES ESPECIALIDAD(ID_Especialidad)
ON DELETE CASCADE;


ALTER TABLE MEDICO_ESPECIALIDAD
ADD constraint FK2_MEDICO_ESPECIALIDAD
FOREIGN KEY(ID_Medico,No_Seguro_Social,RFC,Cedula_Profesional)
REFERENCES MEDICO_INFORMACION_PERSONAL(ID_Medico,No_Seguro_Social,RFC,Cedula_Profesional)
ON DELETE CASCADE;