CREATE TABLE MEDICO_RECETA(
ID_Medico Number,
No_Seguro_Social VARCHAR(255) NOT NULL,
RFC VARCHAR(255) NOT NULL,
Cedula_Profesional VARCHAR(255) NOT NULL,
Nombre VARCHAR(255) NOT NULL,
Apellido_Paterno VARCHAR(255) NOT NULL,
Apellido_Materno VARCHAR(255) NOT NULL,
ID_RECETA NUMBER
);

ALTER TABLE MEDICO_RECETA
ADD constraint PK_MEDICO_RECETA
Primary Key(ID_Medico,No_Seguro_Social,RFC,Cedula_Profesional,ID_RECETA);

ALTER TABLE MEDICO_RECETA
ADD constraint FK1_MEDICO_RECETA
FOREIGN KEY(ID_Medico,No_Seguro_Social,RFC,Cedula_Profesional)
REFERENCES MEDICO_INFORMACION_PERSONAL(ID_Medico,No_Seguro_Social,RFC,Cedula_Profesional)
ON DELETE CASCADE;

ALTER TABLE MEDICO_RECETA
ADD constraint FK2_MEDICO_RECETA
FOREIGN KEY(ID_RECETA)
REFERENCES RECETA_INFORMACION_CONSULTA(ID_RECETA)
ON DELETE CASCADE;

