CREATE TABLE RECETA_INFORMACION_CONSULTA(
ID_Receta Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Medico Number NOT NULL,
Firma ORDIMAGE NOT NULL,
Datos_Paciente Number NOT NULL,
Turno_Consulta Number
);

ALTER TABLE RECETA_INFORMACION_CONSULTA
ADD constraint PK_RECETA_MEDICO
Primary Key(ID_Receta);

CREATE TABLE RECETA_INFORMACION_ESPECIAL(
ID_Receta Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Medico Number,
Firma ORDIMAGE NOT NULL,
PDF VARCHAR(255)
);

ALTER TABLE RECETA_INFORMACION_ESPECIAL
ADD constraint PK_RECETA_ESPECIAL
Primary Key(ID_RECETA,MEDICO);

ALTER TABLE RECETA_INFORMACION_CONSULTA
ADD constraint FK1_RECETA_CONSULTA
FOREIGN KEY(ID_RECETA,MEDICO)
REFERENCES RECETA_INFORMACION_ESPECIAL(ID_RECETA,MEDICO)
ON DELETE CASCADE;
