CREATE TABLE SUCURSAL(
ID_Sucursal Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Direccion VARCHAR(255),
Ciudad VARCHAR(255),
Estado VARCHAR(255)
);

ALTER TABLE SUCURSAL
ADD constraint PK_SUCURSAL
Primary Key(ID_Sucursal);

CREATE TABLE TELEFONOS_SUCURSALES(
ID_Telefono Number GENERATED ALWAYS AS IDENTITY (START with 1 INCREMENT by 1),
Telefono VARCHAR(255)
);

ALTER TABLE TELEFONOS_SUCURSALES
ADD constraint PK_TELEFONOS_SUCURSALES
Primary Key(ID_Telefono);

CREATE TABLE TELEFONO_SUCURSAL(
ID_Telefono Number,
ID_Sucursal Number,
Direccion VARCHAR(255)
);

ALTER TABLE TELEFONO_SUCURSAL
ADD constraint PK_TELEFONO_SUCURSAL
Primary Key(ID_Telefono,ID_Sucursal,Direccion);

ALTER TABLE TELEFONO_SUCURSAL
ADD constraint FK1_TELEFONO_SUCURSAL
FOREIGN KEY(ID_Telefono)
REFERENCES TELEFONOS_SUCURSALES(ID_Telefono)
ON DELETE CASCADE;

ALTER TABLE TELEFONO_SUCURSAL
ADD constraint FK2_TELEFONO_SUCURSAL
FOREIGN KEY(ID_Sucursal)
REFERENCES SUCURSAL(ID_Sucursal)
ON DELETE CASCADE;


