CREATE TABLE SUCURSAL_MEDICAMENTO(
ID_Sucursal Number,
Direccion VARCHAR(255),
Ciudad VARCHAR(255),
Estado VARCHAR(255),
Marca VARCHAR(255),
Nombre VARCHAR(255),
Precio NUMBER(9,0),
Especialidad VARCHAR(255)
);

ALTER TABLE SUCURSAL_MEDICAMENTO
ADD constraint PK_SUCURSAL_MEDIC
Primary Key(ID_SUCURSAL,Marca,Nombre);

ALTER TABLE SUCURSAL_MEDICAMENTO
ADD constraint FK1_SUCURSAL_MEDIC
FOREIGN KEY(ID_SUCURSAL)
REFERENCES SUCURSAL(ID_SUCURSAL)
ON DELETE CASCADE;

ALTER TABLE SUCURSAL_MEDICAMENTO
ADD constraint FK2_SUCURSAL_MEDIC
FOREIGN KEY(Marca,Nombre)
REFERENCES MEDICAMENTO(Marca,Nombre)
ON DELETE CASCADE;
